import IPatient from "./interface/IPatient";

interface ISimulaData {
  count: number;
  patients: IPatient[];
}

const simulaData: ISimulaData = {
  count: 21,
  patients: [{
  email: 'user1@test.com',
  patientName: 'Ultron',
  birthDate: '12/10/200',
  address: {number: 1, street: "Jk"},
}, 
{ email: 'user2@test.com',
patientName: 'Reigan',
birthDate: '12/10/200',
address: {number: 2, street: "Paul Harris"},
},
{ email: 'user3@test.com',
patientName: 'Edward',
birthDate: '12/10/200',
address: {number: 3, street: "René Camargo"},
},
{ email: 'user4@test.com',
patientName: 'test',
birthDate: '12/10/200',
address: {number: 5, street: "test aqui"},
},
{ email: 'user5@gmail.com',
patientName: 'wesley',
birthDate: '12/10/200',
address: {number: 4, street: "test aqui"},
},
{ email: 'user6@hotmail.com',
patientName: 'will',
birthDate: '12/10/200',
address: {number: 6, street: "test aqui"},
},
{ email: 'test7@gmail.com',
patientName: 'wesley safadão',
birthDate: '12/10/200',
address: {number: 7, street: "test aqui"},
},
{ email: 'user8@voiage.com',
patientName: 'hotmail',
birthDate: '12/10/200',
address: {number: 8, street: "test 8 aqui"},
},
{ email: 'user9@hotmail.com',
patientName: 'voiage',
birthDate: '12/10/200',
address: {number: 9, street: "test 9 aqui"},
},
{ email: 'test10@test.com',
patientName: 'test10',
birthDate: '12/10/200',
address: {number: 10, street: "test 10 aqui"},
},
{ email: 'test11@test.com',
patientName: 'test11',
birthDate: '12/10/200',
address: {number: 11, street: "test 11 aqui"},
},
{ email: 'test12@test.com',
patientName: 'test12',
birthDate: '12/10/200',
address: {number: 12, street: "test 12 aqui"},
},
{ email: 'test13@test.com',
patientName: 'test13',
birthDate: '12/10/200',
address: {number: 13, street: "test 13 aqui"},
},
{ email: 'test14@test.com',
patientName: 'test14',
birthDate: '12/10/200',
address: {number: 14, street: "test 14 aqui"},
},
{ email: 'test15@test.com',
patientName: 'test15',
birthDate: '12/10/200',
address: {number: 15, street: "test 15 aqui"},
},
{ email: 'test16@test.com',
patientName: 'test16',
birthDate: '12/10/200',
address: {number: 16, street: "test 16 aqui"},
},
{ email: 'test17@test.com',
patientName: 'test17',
birthDate: '12/10/200',
address: {number: 17, street: "test 17 aqui"},
},
{ email: 'test18@test.com',
patientName: 'test18',
birthDate: '12/10/200',
address: {number: 18, street: "test 18 aqui"},
},
{ email: 'test19@test.com',
patientName: 'test19',
birthDate: '12/10/200',
address: {number: 19, street: "test 19 aqui"},
},
{ email: 'test20@test.com',
patientName: 'test20',
birthDate: '12/10/200',
address: {number: 20, street: "test 20 aqui"},
},
{ email: 'test21@test.com',
patientName: 'test21',
birthDate: '12/10/200',
address: {number: 21, street: "test 21 aqui"},
}
]}

export default simulaData;